//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikitoExpressService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administradore
    {
        public int idAdm { get; set; }
        public int IdUser { get; set; }
        public int idPersona { get; set; }
        public int salario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModicacion { get; set; }
        public bool estado { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual User User { get; set; }
    }
}
