
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChikitoExpressService
{

using System;
    using System.Collections.Generic;
    
public partial class Bebida
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Bebida()
    {

        this.ElementosDeMenus = new HashSet<ElementosDeMenu>();

    }


    public int idBebida { get; set; }

    public int idTipoBebida { get; set; }

    public string Nombre { get; set; }

    public int precio { get; set; }

    public string descripcion { get; set; }

    public bool estado { get; set; }

    public string imagen { get; set; }



    public virtual TiposBebida TiposBebida { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ElementosDeMenu> ElementosDeMenus { get; set; }

}

}
