//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikitoExpressService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChikitoExpressContext2 : DbContext
    {
        public ChikitoExpressContext2()
            : base("name=ChikitoExpressContext2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradore> Administradores { get; set; }
        public virtual DbSet<Articulo> Articulos { get; set; }
        public virtual DbSet<Bebida> Bebidas { get; set; }
        public virtual DbSet<CategoriaArticulo> CategoriaArticulos { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Descuento> Descuentos { get; set; }
        public virtual DbSet<Direccione> Direcciones { get; set; }
        public virtual DbSet<ElementosDeMenu> ElementosDeMenus { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<EnvioDestino> EnvioDestinoes { get; set; }
        public virtual DbSet<EnvioOrigin> EnvioOrigins { get; set; }
        public virtual DbSet<Envio> Envios { get; set; }
        public virtual DbSet<FacturaEnvio> FacturaEnvios { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Ordene> Ordenes { get; set; }
        public virtual DbSet<OrdenesDetalle> OrdenesDetalles { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Plato> Platos { get; set; }
        public virtual DbSet<Provencia> Provencias { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sucursale> Sucursales { get; set; }
        public virtual DbSet<TiposBebida> TiposBebidas { get; set; }
        public virtual DbSet<TiposPlato> TiposPlatos { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersRole> UsersRoles { get; set; }
        public virtual DbSet<Zona> Zonas { get; set; }
    }
}
