
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChikitoExpressService
{

using System;
    using System.Collections.Generic;
    
public partial class Cliente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {

        this.Envios = new HashSet<Envio>();

        this.Facturas = new HashSet<Factura>();

    }


    public int idCliente { get; set; }

    public int idPersona { get; set; }

    public Nullable<int> IdUser { get; set; }

    public Nullable<int> puntoFidelizacion { get; set; }

    public Nullable<System.DateTime> fechaUltimoCompra { get; set; }

    public bool estado { get; set; }



    public virtual Persona Persona { get; set; }

    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Envio> Envios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Factura> Facturas { get; set; }

}

}
