
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChikitoExpressService
{

using System;
    using System.Collections.Generic;
    
public partial class Direccione
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Direccione()
    {

        this.Ordenes = new HashSet<Ordene>();

        this.Personas = new HashSet<Persona>();

        this.Sucursales = new HashSet<Sucursale>();

    }


    public int idDireccion { get; set; }

    public int idZona { get; set; }

    public string calle { get; set; }

    public string Edificio { get; set; }

    public string Apt { get; set; }

    public string casa { get; set; }

    public bool estado { get; set; }



    public virtual Zona Zona { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ordene> Ordenes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Persona> Personas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sucursale> Sucursales { get; set; }

}

}
