
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChikitoExpressService
{

using System;
    using System.Collections.Generic;
    
public partial class Empleado
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empleado()
    {

        this.Facturas = new HashSet<Factura>();

    }


    public int idEmpleado { get; set; }

    public int salario { get; set; }

    public bool estado { get; set; }

    public int IdUser { get; set; }

    public int idPersona { get; set; }



    public virtual Persona Persona { get; set; }

    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Factura> Facturas { get; set; }

}

}
