//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikitoExpressService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Envio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Envio()
        {
            this.EnvioDestinoes = new HashSet<EnvioDestino>();
            this.EnvioOrigins = new HashSet<EnvioOrigin>();
            this.FacturaEnvios = new HashSet<FacturaEnvio>();
        }
    
        public int idEnvio { get; set; }
        public string nombreDestinatario { get; set; }
        public string nombreRemitente { get; set; }
        public string estadoSolicitud { get; set; }
        public int idCliente { get; set; }
        public int idArticulo { get; set; }
        public int precio { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvioDestino> EnvioDestinoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvioOrigin> EnvioOrigins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaEnvio> FacturaEnvios { get; set; }
    }
}
