//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikitoExpressService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int idFacturas { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<int> idDescuentos { get; set; }
        public int idOrden { get; set; }
    }
}
