//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikitoExpressService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaEnvio
    {
        public int idFactura { get; set; }
        public int costoEnvio { get; set; }
        public string estadoFactura { get; set; }
        public int idEnvio { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Envio Envio { get; set; }
    }
}
