
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChikitoExpressService
{

using System;
    using System.Collections.Generic;
    
public partial class Persona
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Persona()
    {

        this.Administradores = new HashSet<Administradore>();

        this.Clientes = new HashSet<Cliente>();

        this.Empleados = new HashSet<Empleado>();

    }


    public int idPersona { get; set; }

    public int idDireccion { get; set; }

    public string Documento { get; set; }

    public string primerNombre { get; set; }

    public string segundoNombre { get; set; }

    public string primerApellido { get; set; }

    public string segundoApellido { get; set; }

    public string telefono { get; set; }

    public string nacionalidad { get; set; }

    public System.DateTime fechaNacimiento { get; set; }

    public string email { get; set; }

    public System.DateTime fechaCreacion { get; set; }

    public Nullable<System.DateTime> fechaModicacion { get; set; }

    public bool estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Administradore> Administradores { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cliente> Clientes { get; set; }

    public virtual Direccione Direccione { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Empleado> Empleados { get; set; }

}

}
