
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChikitoExpressService
{

using System;
    using System.Collections.Generic;
    
public partial class ViewEmpleado
{

    public int idEmpleado { get; set; }

    public string Username { get; set; }

    public string Documento { get; set; }

    public string primerNombre { get; set; }

    public string segundoNombre { get; set; }

    public string primerApellido { get; set; }

    public string segundoApellido { get; set; }

    public string telefono { get; set; }

    public string nacionalidad { get; set; }

    public System.DateTime fechaNacimiento { get; set; }

    public string email { get; set; }

    public string calle { get; set; }

    public string Edificio { get; set; }

    public string Apt { get; set; }

    public string casa { get; set; }

    public string nombre { get; set; }

    public int salario { get; set; }

    public bool Activo { get; set; }

    public bool Online { get; set; }

    public string Roles { get; set; }

}

}
