
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChikitoExpressService
{

using System;
    using System.Collections.Generic;
    
public partial class ViewFacturasEnvio
{

    public int idFactura { get; set; }

    public int costoEnvio { get; set; }

    public int idEnvio { get; set; }

    public string nombreDestinatario { get; set; }

    public string nombreRemitente { get; set; }

    public int Valor { get; set; }

    public string descripcionArticulo { get; set; }

    public int cantidadArticulo { get; set; }

    public string categoria { get; set; }

}

}
