
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChikitoExpressService
{

using System;
    using System.Collections.Generic;
    
public partial class ViewFactura
{

    public int idFacturas { get; set; }

    public int idCliente { get; set; }

    public int idEmpleado { get; set; }

    public string telefono { get; set; }

    public string primerNombre { get; set; }

    public string calle { get; set; }

    public string Edificio { get; set; }

    public string Apt { get; set; }

    public string casa { get; set; }

    public string Zona { get; set; }

    public string Bebida { get; set; }

    public string deliveryOpcion { get; set; }

    public int BebidaPrecio { get; set; }

    public string Plato { get; set; }

    public int Platoprecio { get; set; }

}

}
