
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ChikitoExpressService
{

using System;
    using System.Collections.Generic;
    
public partial class ViewEnvio
{

    public int idEnvio { get; set; }

    public string estadoSolicitud { get; set; }

    public string Origin { get; set; }

    public string Destino { get; set; }

}

}
